import { useEffect } from "react"
import { useRouter } from 'next/router';
import Head from 'next/head'
import styles from '../styles.module.css'

const Index = () => {
  const router = useRouter()
  useEffect(() => {
    return () => {
      if(router.pathname === "/") router.replace(`/g/${process.env.GAME_ID}`)
    }
  }, [router]);

  return (
    <div className={styles.container}>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    </div>
  )
}

export default Index
